<?php
/**
 * CosmoCommerce
 *
 * NOTICE OF LICENSE
 * CosmoCommerce Commercial License 
 * support@cosmocommerce.com
 *
 * @category   CosmoCommerce
 * @copyright  Copyright (c) 2009 CosmoCommerce,LLC. (http://www.cosmocommerce.com)
 * @license	     CosmoCommerce Commercial License(http://www.cosmocommerce.com/cosmocommerce_commercial_license.txt)
 */
?>






<fieldset class="form-list">
	<?php $_code=$this->getMethodCode() ?>
	<ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<li>
			<?php echo $this->__('You will be redirected to CreditCard Gateway when you place an order.') ?>
		</li>
	</ul>
</fieldset>