<?php
/**
 * CosmoCommerce
 *
 * NOTICE OF LICENSE
 * CosmoCommerce Commercial License 
 * support@cosmocommerce.com
 *
 * @category   CosmoCommerce
 * @copyright  Copyright (c) 2009 CosmoCommerce,LLC. (http://www.cosmocommerce.com)
 * @license	     CosmoCommerce Commercial License(http://www.cosmocommerce.com/cosmocommerce_commercial_license.txt)
 */
?>





<img style='border:none;margin-left:12px;' src="<?php echo $this->getskinurl('images/card.png'); ?>">
<fieldset class="form-list">
	<?php $_code=$this->getMethodCode() ?>
	<ul id="payment_form_<?php echo $_code ?>" style="display:none">
		<li>
			<?php echo $this->__('') ?>
		</li>
	</ul>
</fieldset>