<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    FirstTeam
 * @package     Fashionpay_FirstTeam
 * @copyright   Copyright (c) 2009-2015 FirstTeam.
 */
?>
<body onload="showLeftTime()">
<div class="form-divst">
<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
     <?php  if(strstr($_typeCode,'VI')){ ?>

         <div style="float:left;"><img src="<?php echo $this->getSkinUrl('images/FirstTeam/visa_70.png') ?>" /></div>

     <?php  } if(strstr($_typeCode,'MC')){  ?>

         <div style="float:left;"><img src="<?php echo $this->getSkinUrl('images/FirstTeam/mastercard_70.png') ?>" /></div>

    <?php  } if(strstr($_typeCode,'JCB')){  ?>
        
        <div style="float:left;"> <img src="<?php echo $this->getSkinUrl('images/FirstTeam/jcb_70.png') ?>" /></div>

    <?php  } if(strstr($_typeCode,'AE')){  ?>

         <div style="float:left;"> <img src="<?php echo $this->getSkinUrl('images/FirstTeam/american_express_70.png') ?>" /></div>
    
<?php } endforeach ?>


<br/>
</div>
<fieldset class="form-divst" style="clear:both">
	<?php $_code=$this->getMethodCode() ?>
	<ul class="form-list" id="payment_form_<?php echo $_code ?>">
    <li>
        <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type_ek]" title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
            <?php $_ccType = $this->getInfoData('cc_type') ?>
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number_ek]" maxlength="16" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
			<input type="hidden" id="<?php echo $_code ?>_cc_payment_time" name="payment[cc_payment_time]" value=""/>
			<input type="hidden" name="payment[cc_clientIP]" value="" id="FirstTeam_cc_clientIP"/>
				<script language="javascript" type="text/javascript" src="http://pv.sohu.com/cityjson?ie=utf-8"></script>    
				<script>
				 document.getElementById("FirstTeam_cc_clientIP").value=returnCitySN.cip;
				</script> 
				<script language="javascript" type="text/javascript">
				<!--
				/** get client time **/
				//获得当前时间,刻度为一千分一秒
				var initializationTime=(new Date()).getTime();
				function showLeftTime()
				{
				var now=new Date();
				var year=now.getFullYear();
				var month=now.getMonth()+1;
				var day=now.getDate();
				var hour=now.getHours();
				var minute=now.getMinutes();
				var seconds=now.getSeconds();

					if(month<10){
						month="0"+month;
					}
					if(day<10){
						day="0"+day;
					}
					if(hour<10){
						hour="0"+hour;
					}
					if(minute<10){
						minute="0"+minute;
					}
					if(seconds<10){
						seconds="0"+seconds;
					}
					
				document.getElementById("<?php echo $_code ?>_cc_payment_time").value =""+year+"-"+month+"-"+day+" "+hour+":"+minute+":"+seconds+"";
				//一秒刷新一次显示时间
				var timeID=setTimeout(showLeftTime,1000);
				}
				//-->
				</script>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
        <div class="input-box">
            <div class="v-fix">
            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>                              
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month_ek]" class="month validate-cc-exp required-entry">
              <option selected="selected" value="">Month</option>
                <option value="01">01 - January</option>
                <option value="02">02 - February</option>
                <option value="03">03 - March</option>
                <option value="04">04 - April</option>
                <option value="05">05 - May</option>
                <option value="06">06 - June</option>
                <option value="07">07 - July</option>
                <option value="08">08 - August</option>
                <option value="09">09 - September</option>
                <option value="10">10 - October</option>
                <option value="11">11 - November</option>
                <option value="12">12 - December</option>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year_ek]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="password" maxlength="3" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid_ek]" value="" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
    <?php if ($this->hasSsCardType()): ?>
    <li id="<?php echo $_code ?>_cc_type_ss_div">
        <ul class="inner-form">
            <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue_ek" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
            <li>
                <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                <span class="input-box">
                    <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue_ek]" value="" />
                </span>
            </li>

       
            <li class="adv-container">&nbsp;</li>
        </ul>
		
       <script type="text/javascript">
			//<![CDATA[
				var SSChecked<?php echo $_code ?> = function() {
					var elm = $('<?php echo $_code ?>_cc_type');
					if (['SS','SM','SO'].indexOf(elm.value) != -1) {
						$('<?php echo $_code ?>_cc_type_ss_div').show();
					} else {
						$('<?php echo $_code ?>_cc_type_ss_div').hide();
					}
				};

				Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
				SSChecked<?php echo $_code ?>();
			//]]>
			</script>
    </li>
    <?php endif; ?>
</ul>
</fieldset>
</body>